"""armd 硬件后端。"""

from .base import (
    Backend,
    BackendClosedError,
    BackendError,
    BackendLimits,
    DEFAULT_LIMITS,
    DISCONNECTED_SENTINEL,
    ESTOP_RECOVERY_DAMPING_KD,
    ESTOP_RECOVERY_GRIPPER_KD,
    FrameMode,
    IDLE_DAMPING_KD,
    JointFrame,
    LimitViolationError,
    MotorSnapshot,
    STALE_AFTER_S,
    estop_recovery_frame,
    idle_damping_frame,
)
from .sim import SimBackend
from .real import (
    DEFAULT_MOTOR_TIMEOUT_MS,
    MIN_SAFE_STATE_QUERY_FIRMWARE,
    RealBackend,
    SdkAuditError,
    SdkAuditResult,
    audit_sdk_source,
)

__all__ = [
    "Backend",
    "BackendClosedError",
    "BackendError",
    "BackendLimits",
    "DEFAULT_LIMITS",
    "DISCONNECTED_SENTINEL",
    "ESTOP_RECOVERY_DAMPING_KD",
    "ESTOP_RECOVERY_GRIPPER_KD",
    "FrameMode",
    "IDLE_DAMPING_KD",
    "JointFrame",
    "LimitViolationError",
    "MotorSnapshot",
    "STALE_AFTER_S",
    "estop_recovery_frame",
    "idle_damping_frame",
    "SimBackend",
    "DEFAULT_MOTOR_TIMEOUT_MS",
    "MIN_SAFE_STATE_QUERY_FIRMWARE",
    "RealBackend",
    "SdkAuditError",
    "SdkAuditResult",
    "audit_sdk_source",
]
